### ISSUE TITLE
Sharing our test image

### ISSUE THREAD

**Issue by kaiyou** [Chocobozzz/PeerTube-Docker#5]
More of a pointer than a bug report, but we are currently testing a homemade image at TeDomum : https://github.com/tedomum/docker-peertube

It is intentionally based on a node Alpine base image (both for size and security) and does not include any reverse proxy or such. Feel free to steal any useful bits.

**Comment by Chocobozzz** [comment]
Hi,

thanks but I'll remove this repository to merge the dockerfiles in the main repository: https://github.com/Chocobozzz/PeerTube/tree/develop/support/docker

Feel free to make a PR to add a production image :)
